import { prisma } from "@/lib/prisma";
import { logAutomation } from "@/lib/workflows";

type AutopilotResult = {
  leadUpdates: number;
  scheduledOrders: number;
  assignedOrders: number;
  recurringGenerated: number;
  followupsGenerated: number;
  invoicesMarkedSent: number;
};

export async function runOpsAutopilot(): Promise<AutopilotResult> {
  let leadUpdates = 0;
  let scheduledOrders = 0;
  let assignedOrders = 0;
  let recurringGenerated = 0;
  let followupsGenerated = 0;
  let invoicesMarkedSent = 0;

  const freshLeads = await prisma.lead.findMany({
    where: { status: "New" },
    orderBy: { createdAt: "asc" },
    take: 25,
  });

  for (const lead of freshLeads) {
    const upgradedStatus = lead.source.toLowerCase().includes("referral") ? "Qualified" : "Contacted";
    await prisma.lead.update({ where: { id: lead.id }, data: { status: upgradedStatus } });
    await logAutomation("lead_triage", "lead", lead.id, `Lead moved from New to ${upgradedStatus}.`, {
      source: lead.source,
    });
    leadUpdates += 1;
  }

  const unassigned = await prisma.workOrder.findMany({
    where: { status: "Unassigned" },
    orderBy: [{ priority: "desc" }, { createdAt: "asc" }],
    take: 20,
  });

  for (const workOrder of unassigned) {
    await prisma.workOrder.update({
      where: { id: workOrder.id },
      data: {
        status: "Scheduled",
        scheduledDate: workOrder.scheduledDate ?? new Date(),
      },
    });
    await logAutomation("dispatch_autoschedule", "work_order", workOrder.id, "Work order auto-scheduled by autopilot.");
    scheduledOrders += 1;
  }

  const availableTechs = await prisma.technician.findMany({
    where: { status: "Available" },
    orderBy: { name: "asc" },
    take: 20,
  });
  const scheduleQueue = await prisma.workOrder.findMany({
    where: { status: "Scheduled" },
    include: { assignments: true },
    orderBy: { createdAt: "asc" },
    take: 50,
  });
  let techCursor = 0;
  if (availableTechs.length > 0) {
    for (const workOrder of scheduleQueue) {
      if (workOrder.assignments.length > 0) continue;
      const chosen = availableTechs[techCursor % availableTechs.length];
      techCursor += 1;
      await prisma.workOrderAssignment.create({
        data: {
          workOrderId: workOrder.id,
          technicianId: chosen.id,
          note: "Assigned by daily autopilot.",
        },
      });
      await logAutomation(
        "autopilot_assignment",
        "work_order",
        workOrder.id,
        `Assigned technician ${chosen.name} automatically.`
      );
      assignedOrders += 1;
    }
  }

  const now = new Date();
  const recurringDue = await prisma.recurringJob.findMany({
    where: { active: true, nextRunAt: { lte: now } },
    include: { customer: true },
    take: 50,
  });
  for (const item of recurringDue) {
    await prisma.workOrder.create({
      data: {
        title: `${item.title} (${item.frequency})`,
        customerId: item.customerId,
        status: "Unassigned",
        priority: item.priority,
        notes: `Generated by autopilot from recurring job ${item.id}.`,
      },
    });

    const next = new Date(now);
    if (item.frequency === "Daily") next.setDate(next.getDate() + item.intervalCount);
    else if (item.frequency === "Weekly") next.setDate(next.getDate() + item.intervalCount * 7);
    else if (item.frequency === "Biweekly") next.setDate(next.getDate() + item.intervalCount * 14);
    else next.setMonth(next.getMonth() + item.intervalCount);

    await prisma.recurringJob.update({ where: { id: item.id }, data: { nextRunAt: next } });
    await logAutomation("autopilot_recurring", "recurring_job", item.id, `Generated recurring work order for ${item.customer.name}.`);
    recurringGenerated += 1;
  }

  const readyToInvoice = await prisma.workOrder.findMany({
    where: { status: "Ready to Invoice" },
    include: { invoices: true },
    take: 20,
  });

  for (const workOrder of readyToInvoice) {
    if (workOrder.invoices.length === 0) {
      const count = await prisma.invoice.count();
      const invoiceNumber = `INV-${(count + 9001).toString()}`;
      await prisma.invoice.create({
        data: {
          invoiceNumber,
          status: "Draft",
          amountCents: 0,
          customerId: workOrder.customerId,
          workOrderId: workOrder.id,
          notes: "Created by daily autopilot from Ready to Invoice workflow.",
        },
      });
      await logAutomation(
        "auto_invoice_create",
        "work_order",
        workOrder.id,
        `Draft invoice ${invoiceNumber} auto-created for ready-to-invoice work order.`
      );
      followupsGenerated += 1;
    }
  }

  const drafts = await prisma.invoice.findMany({
    where: { status: "Draft" },
    orderBy: { createdAt: "asc" },
    take: 10,
  });

  for (const invoice of drafts) {
    await prisma.invoice.update({
      where: { id: invoice.id },
      data: { status: "Sent" },
    });
    await logAutomation("invoice_send_queue", "invoice", invoice.id, `Invoice ${invoice.invoiceNumber} moved from Draft to Sent.`);
    invoicesMarkedSent += 1;
  }

  return {
    leadUpdates,
    scheduledOrders,
    assignedOrders,
    recurringGenerated,
    followupsGenerated,
    invoicesMarkedSent,
  };
}
